const REQ_LOGIN = 'REQ_LOGIN'
const REQ_LOGIN_SUCCESS = 'REQ_LOGIN_SUCCESS'
const REQ_LOGIN_FAILED = 'REQ_LOGIN_FAILED'

const GET_LIST_NOTES = 'GET_LIST_NOTES'
const GET_LIST_NOTES_SUCCESS = 'GET_LIST_NOTES_SUCCESS'
const GET_LIST_NOTES_FAILED = 'GET_LIST_NOTES_FAILED'

const ADD_LIST_NOTE = 'ADD_LIST_NOTE'
const ADD_LIST_NOTE_SUCCESS = 'ADD_LIST_NOTE_SUCCESS'
const ADD_LIST_NOTE_FAILED = 'ADD_LIST_NOTE_FAILED'

const UPDATE_LIST_NOTE = 'UPDATE_LIST_NOTE'
const UPDATE_LIST_NOTE_SUCCESS = 'UPDATE_LIST_NOTE_SUCCESS'
const UPDATE_LIST_NOTE_FAILED = 'UPDATE_LIST_NOTE_FAILED'

const LOGOUT = 'LOGOUT'

export {
  REQ_LOGIN,
  REQ_LOGIN_FAILED,
  REQ_LOGIN_SUCCESS,
  GET_LIST_NOTES,
  GET_LIST_NOTES_FAILED,
  GET_LIST_NOTES_SUCCESS,
  ADD_LIST_NOTE,
  ADD_LIST_NOTE_FAILED,
  ADD_LIST_NOTE_SUCCESS,
  UPDATE_LIST_NOTE,
  UPDATE_LIST_NOTE_FAILED,
  UPDATE_LIST_NOTE_SUCCESS,
  LOGOUT,
}
